from torch import Tensor
from typing import Callable, Optional


class Offloader:
    def __init__(self, filename: str, n_entries: int, backend: str = 'uring') -> None: ...
    def write(self, tensor: Tensor, key: str, callback: Optional[Callable[[], None]] = None) -> None: ...
    def read(self, tensor: Tensor, key: str, callback: Optional[Callable[[], None]] = None) -> None: ...
    def sync_write_events(self) -> None: ...
    def sync_read_events(self) -> None: ...
    def synchronize(self) -> None: ...
